name: "Home Manager import"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  home-manager-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pairs:
          - branch: release-23.05
            channel: nixos-23.05
          - branch: master
            channel: nixos-unstable
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:${{ matrix.pairs.channel }}:/home/runner/.nix-defexpr/channels

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Add Home Manager
        run: nix-channel --add https://github.com/nix-community/home-manager/archive/${{ matrix.pairs.branch }}.tar.gz home-manager

      - name: Update channels
        run: nix-channel --update

      - name: Install Home Manager
        run: nix-shell 'https://github.com/nix-community/home-manager/archive/${{ matrix.pairs.branch }}.tar.gz' -A install

      - name: Copy configuration file
        run: |
          mkdir -p $XDG_CONFIG_HOME/home-manager
          cp -f .github/home-manager.nix $XDG_CONFIG_HOME/home-manager/home.nix

      - name: Rebuild Home Manager configuration
        run: home-manager switch --show-trace
