name: "Package Build"

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  package-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - nixos-21.11
          - nixos-22.05
          - nixos-unstable
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:${{ matrix.channel }}
      - run: nix-shell .github/shadow-packages.nix
