name: "Package Build"

on: [push, pull_request]

jobs:
  package-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - nixos-22.05
          - nixos-unstable
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:${{ matrix.channel }}
      - run: nix-shell .github/shadow-packages.nix
