name: "Package Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package-build:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix flake check --impure
