name: "Package Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - nixos-23.05
          - nixos-unstable
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:${{ matrix.channel }}
      - run: nix-shell .github/shadow-packages.nix
