name: Update upstream-info.json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  update-upstream-info:
    name: Update Upstream information
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Update Upstream information file
        run: ./update.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          author: "dependabot[bot] <dependabot[bot]@users.noreply.github.com>"
          commit-message: "Update upstream-info.json"
          title: "Update upstream-info.json"
          assignees: "anthonyroussel"
          reviewers: "anthonyroussel"
